use super::*; 

mod create_window;
pub use create_window::value_masks;


// predefined atoms
pub const SECONDARY: Atom = Atom(2);
pub const ARC: Atom = Atom(3);
pub const ATOM: Atom = Atom(4);
pub const BITMAP: Atom = Atom(5);
pub const CARDINAL: Atom = Atom(6);
pub const COLORMAP: Atom = Atom(7);
pub const CURSOR: Atom = Atom(8);
pub const CUT_BUFFER: Atom = Atom(0);
pub const CUT_BUFFER1: Atom = Atom(10);
pub const CUT_BUFFER2: Atom = Atom(11);
pub const CUT_BUFFER3: Atom = Atom(12);
pub const CUT_BUFFER4: Atom = Atom(13);
pub const CUT_BUFFER5: Atom = Atom(14);
pub const CUT_BUFFER6: Atom = Atom(15);
pub const CUT_BUFFER7: Atom = Atom(16);
pub const DRAWABLE: Atom = Atom(17);
pub const FONT: Atom = Atom(18);
pub const INTEGER: Atom = Atom(19);
pub const PIXMAP: Atom = Atom(20);
pub const POINT: Atom = Atom(21);
pub const RECTANGLE: Atom = Atom(22);
pub const RESOURCE_MANAGER: Atom = Atom(23);
pub const RGB_COLOR_MAP: Atom = Atom(24);
pub const RGB_BEST_MAP: Atom = Atom(25);
pub const RGB_BLUE_MAP: Atom = Atom(26);
pub const RGB_DEFAULT_MAP: Atom = Atom(27);
pub const RGB_GRAY_MAP: Atom = Atom(28);
pub const RGB_GREEN_MAP: Atom = Atom(29);
pub const RGB_RED_MAP: Atom = Atom(30);
pub const STRING: Atom = Atom(31);
pub const VISUALID: Atom = Atom(32);
pub const WINDOW: Atom = Atom(33);
pub const WM_COMMAND: Atom = Atom(34);
pub const WM_HINTS: Atom = Atom(35);
pub const WM_CLIENT_MACHINE: Atom = Atom(36);
pub const WM_ICON_NAME: Atom = Atom(37);
pub const WM_ICON_SIZE: Atom = Atom(38);
pub const WM_NAME: Atom = Atom(39);
pub const PRIMARY: Atom = Atom(1);
pub const WM_NORMAL_HINTS: Atom = Atom(40);
pub const WM_SIZE_HINTS: Atom = Atom(41);
pub const WM_ZOOM_HINTS: Atom = Atom(42);
pub const MIN_SPACE: Atom = Atom(43);
pub const NORM_SPACE: Atom = Atom(44);
pub const MAX_SPACE: Atom = Atom(45);
pub const END_SPACE: Atom = Atom(46);
pub const SUPERSCRIPT_X: Atom = Atom(47);
pub const SUPERSCRIPT_Y: Atom = Atom(48);
pub const SUBSCRIPT_X: Atom = Atom(49);
pub const SUBSCRIPT_Y: Atom = Atom(50);
pub const UNDERLINE_POSITION: Atom = Atom(51);
pub const UNDERLINE_THICKNESS: Atom = Atom(52);
pub const STRIKEOUT_ASCENT: Atom = Atom(53);
pub const STRIKEOUT_DESCENT: Atom = Atom(54);
pub const ITALIC_ANGLE: Atom = Atom(55);
pub const X_HEIGHT: Atom = Atom(56);
pub const QUAD_WIDTH: Atom = Atom(57);
pub const WEIGHT: Atom = Atom(58);
pub const POINT_SIZE: Atom = Atom(59);
pub const RESOLUTION: Atom = Atom(60);
pub const COPYRIGHT: Atom = Atom(61);
pub const NOTICE: Atom = Atom(62);
pub const FONT_NAME: Atom = Atom(63);
pub const FAMILY_NAME: Atom = Atom(64);
pub const FULL_NAME: Atom = Atom(65);
pub const CAP_HEIGHT: Atom = Atom(66);
pub const WM_CLASS: Atom = Atom(67);
pub const WM_TRANSIENT_FOR: Atom = Atom(68);